### ISSUE TITLE
Activer le DHT

### ISSUE THREAD

**Issue by Machou** [adriengibrat/torrent-rw#10]
Salut,

Je crois que la fonctionnalité d'activer le DHT d'un torrent n'est pas disponible me semble-t-il.

Possible de l'ajouter ?

Merci

pour plus d'info sur le DHT : http://fr.wikipedia.org/wiki/Table_de_hachage_distribu%C3%A9e

**Comment by Karlingue** [comment]
Toujours rien ?

**Comment by adriengibrat** [comment]
J'accepte les merge request, mais je ne maintiens plus ce projet, vu que je ne l'utilise pas personnellement...
Des volontaires?

**Comment by Machou** [comment]
Dommage =(

**Comment by Machou** [comment]
Pour ceux qui peuvent le faire, y'a un scrapper udp ici :

https://github.com/hush2/torrentedit

**Comment by thamniyomroots** [comment]
#10

**Comment by Machou** [comment]
To scrape udp & http i use this class : https://github.com/medariox/scrapeer

Scrapeer, a tiny PHP library that lets you scrape HTTP(S) and UDP trackers for torrent information.
