### ISSUE TITLE
Missing charset ?

### ISSUE THREAD

**Issue by skol-pro** [adriengibrat/torrent-rw#23]
There is no charset specified (like charset=utf-8) : 
https://github.com/adriengibrat/torrent-rw/blob/master/Torrent.php#L362

Intentional ?

**Comment by adriengibrat** [comment]
> Intentional ?
nope, it's really missing !
I'm not using or actively maintaining this projetc, butt I'll accept merge request ;)

**Comment by adriengibrat** [comment]
PR are welcome
