### ISSUE TITLE
Can't get info of particular torrent

### ISSUE THREAD

**Issue by ziphir** [adriengibrat/torrent-rw#24]
Regardless of his content, I can't get the content of this torrent, I guess there is an error in the bencoding function.
<a rel="nofollow" href="http://88.80.6.5/torrent/76cd5738e9975768d20ae7eea1bf89b76fe82bff">TEST</a>

**Comment by adriengibrat** [comment]
far too late, file is not accessible anymore, sorry i'm nclosing this
