### ISSUE TITLE
Ajouter la date de création du torrent

### ISSUE THREAD

**Issue by Machou** [adriengibrat/torrent-rw#35]
Bonjour Adrien,

Je me doute que tu ne maintiens plus trop cette class, mais peux-tu, à l'occasion, ajouter les informations concernant la date de création du torrent.

Ca ressemble à :

creation datei1483384502

Cordialement

**Comment by adriengibrat** [comment]
'creation date' semble être une méta donnée comme une autre, tu peux simplement créer les torrents en  passant la donnée dans les meta je pense:

```php
Torrent($file_or_folder_path, ['announce' => $announce_url, 'creation date' => time()])
```

**Comment by Machou** [comment]
Non, c'est pour récupérer la date de création du torrent, elle est dans tous les fichiers torrents.

Comme quand tu récupères les announces.

**Comment by adriengibrat** [comment]
`$torrent['creation date']` ?

Peux tu fournir un torrent avec un 'creation date' , stp ?

**Comment by Machou** [comment]
Tous les torrents ont une 'creation date', voici quelques exemples de torrent : (tous légaux, ce sont des distributions Linux)

http://torrage.info/torrent.php?h=0403FB4728BD788FBCB67E87D6FEB241EF38C75A
http://torrage.info/torrent.php?h=4096EC129404689CEB8056D907E384FF872C2CE9
http://torrage.info/torrent.php?h=0249250B53385B1429323D93CB7467B45D097212
http://torrage.info/torrent.php?h=382884E90E221577A0E95470E739A33D6EA5697C
http://torrage.info/torrent.php?h=723BC28F9B6F924CCA68CCDFF96B6190566CA6B4
http://torrage.info/torrent.php?h=6C6A833040D440CF2075E8045A08A0119B02690C
http://torrage.info/torrent.php?h=30DB5DEE32A1B87C44169F754C088C18D3ED0785

:)

**Comment by adriengibrat** [comment]
Commit direct dans le master  0bf9b952663ec968bf0693db88b4682d133e714b

J'ai pas testé correctement...
