### ISSUE TITLE
Large torrent size.

### ISSUE THREAD

**Issue by jhemmmm** [adriengibrat/torrent-rw#38]
I tried using this class with some that has 4mb size. It takes forever.

**Comment by thamniyomroots** [comment]
#38

**Comment by adriengibrat** [comment]
Please provide test files!

**Comment by MaeJhem** [comment]
Damn, I forgot the torrent file.
It is 4mb file torrent size with so many many files. It is a game, with some kind of logs/data/etc. That's why it is many.
