### ISSUE TITLE
Error while reading some torrent file

### ISSUE THREAD

**Issue by moji1873** [adriengibrat/torrent-rw#40]
Hello
When I try to read this torrent file:
https://pirateiro.com/download-t64/download
I get the following error:

> PHP Fatal error:  Cannot access property started with '\0' in Torrent.class.php on line 113

I temporarily solved the issue by changing the following lines:
```
        foreach( $meta as $key => $value )
        {
            $key = trim($key);
            $this->{$key} = $value;
        }
```

but I don't know if I might be breaking something or not!
This might be useful:
https://cweiske.de/tagebuch/php-property-started-nul.htm

**Comment by adriengibrat** [comment]
sounds legit to trim the key.
Please submit a merge request ;)

**Comment by moji1873** [comment]
sorry I'm not familiar with git :)
