### ISSUE TITLE
Kapurush aka The Coward (1965) 720p.BRrip.Sujaidr (pimprg) (Criterion)

### ISSUE THREAD

**Issue by adrfanatic** [adriengibrat/torrent-rw#42]
Its a earnest request as i see this torrent is created by you, Do you have any idea whether there are any updated trackers to this as i cant find any seeds and i have been waiting for several days now.

Please Help

**Comment by adriengibrat** [comment]
Hello,

I'm not seeding any torrent, I haven't created any torrent, I just wrote
the script that have created/modified the torrent file, and my script added
info about the soft and author in torrent metadata.

Any torrent that contains password protected rar is 99%
crap/malware/spamware.

I can't help.

**Comment by darkalchemy** [comment]
This is not related to this project, except, that it was used to create a torrent.
