### ISSUE TITLE
Deprecated: Function create_function() is deprecated

### ISSUE THREAD

**Issue by Machou** [adriengibrat/torrent-rw#46]
hello

On this lines :

https://github.com/adriengibrat/torrent-rw/blob/bb3445fdf22138f5c78d0a00b5e979bf632dfb77/Torrent.php#L756
https://github.com/adriengibrat/torrent-rw/blob/bb3445fdf22138f5c78d0a00b5e979bf632dfb77/Torrent.php#L889

in PHP 7.2 the function create_function() is deprecated

possible to change this ?

**Comment by darkalchemy** [comment]
Thanks. I was just doing the same for another project. I have tested this on roughly 100 torrents without issue.

9ffbe46
