### ISSUE TITLE
expected value (list, dict, int or string) in bencoded string

### ISSUE THREAD

**Issue by Wertos** [adriengibrat/torrent-rw#48]
```
$torrent = new Torrent($torrent_file);
$torrent->send();
```
Open in Qbittorrent 4.0.4 and http://torrenteditor.com/

**Comment by adriengibrat** [comment]
And? The error in the issue title says the torrent is empty or lacking basic information...

It seems very related to your `$torrent_file`  variable being empty or pointing to empty/invalid torrent.

Not much we can do here ;)
