### ISSUE TITLE
Integratye class Scrapeer to scrape UDP

### ISSUE THREAD

**Issue by Machou** [adriengibrat/torrent-rw#52]
**EN**
Hello,

Is it possible to integrate the PHP Scrapeer class to scrape torrents in UDP?

https://github.com/medariox/scrapeer

**FR**
Bonjour,

Est-ce possible d'intégrer la class PHP Scrapeer pour scraper les torrents en UDP ?

https://github.com/medariox/scrapeer

**Comment by darkalchemy** [comment]
I will look into this. How do you see it being used? 

I don't have any torrents with udp trackers, could you upload one and share the link?

**Comment by Machou** [comment]
> I will look into this. How do you see it being used?
> 
> I don't have any torrents with udp trackers, could you upload one and share the link?

You can find à torrent with UDP easiest :)

**Comment by darkalchemy** [comment]
No. None of the trackers that i am familiar with use udp, so i don't even know where to look.

**Comment by darkalchemy** [comment]
I have updated the changes/demo branch. Please take a look and see if it is working for you. I have tested everything except send torrent to client as I think that would be done from a webserver.

These are breaking changes and would need a new minor version.

The changes/demo adds the scrape udp and addresses the issues in both current pull requests. #54 and #50.
